name: Syntropy Agent CI

on:
  push:
    branches: master

jobs:
  create-container:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      -
        name: test
        run: echo running on branch ${GITHUB_REF}
      -
        name: SANDBOX Build and push
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            syntropynet/agent:latest
            syntropynet/agent:sandbox
      - name: DEVEL Build and push
        if: contains(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: syntropynet/agent:devel
      - name: PROD Build and push
        # BRANCH_STABLE_VERSION
        if: github.ref == 'refs/heads/v0.0.70'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            syntropynet/agent:prod
            syntropynet/agent:stable
